name: Check pre-commit Hooks

on:
  workflow_dispatch:
  push:
    branches:
      - "*"

jobs:
  check-pre-commit-hooks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: prefix-dev/setup-pixi@v0.8.11
        with:
          pixi-version: v0.49.0
          environments: dev-commit
          activate-environment: true
      - name: Install pre-commit and hooks
        run: pre-commit install
      - name: Run pre-commit hooks
        run: pre-commit run -a
